### ISSUE TITLE
Feat: allow for custom mark for the cartogram view so you could pass pie charts

### ISSUE THREAD

**Issue by susielu** [emeeks/react-dorling-map#11]

**Comment by emeeks** [comment]
`0.0.10` now honors `customMark` which takes a function and returns JSX SVG. The function will be passed `(datapoint, index)` with the datapoint having (along with the base feature) `r`, `x`, `y` allowing you to position a custom mark. So you could do something simple like: `d => <circle r={d.r} cx={d.x} cy={d.y} />` or more complex like `d => <g transform={'translate(${d.x},${d.y})'}><circle r={d.r} /><rect width={10} height={10} /></g>`

The component also accepts a `customTransition` which is a value in seconds to determine the transition from the default circles to your custom mark. The transition is a simple opacity 0 to 1 for the custom mark.

![dorling](https://user-images.githubusercontent.com/495634/51999231-1f809100-246f-11e9-97f1-89d73312fd3a.gif)
